import {StyleSheet, Dimensions} from 'react-native'
const { width } = Dimensions.get("window");

export default StyleSheet.create({
    container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  topPart: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  topText: {
    fontSize: 40,
    color: "#000",
    textAlign: 'center',
    fontWeight: 'bold',
    marginBottom: 40,
  },
  inputContainer: {
    width: '100%',
    marginBottom: 20,
    position: 'relative',
  },
  input: {
    width: '100%',
    backgroundColor: '#DFDFDF',
    paddingVertical: 18,
    paddingHorizontal: 20,
    paddingRight: 50,
    borderRadius: 5,
    fontSize: 16,
    color: '#000',
    borderBottomWidth: 2,
    borderBottomColor: '#000',
  },
  clearButton: {
    position: 'absolute',
    right: 15,
    top: '50%',
    transform: [{ translateY: -10 }],
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#49454F',
    justifyContent: 'center',
    alignItems: 'center',
  },
  clearButtonText: {
    color: '#fff',
    fontSize: 10,
  },
  bottomPart: {
    flex: 1,
    backgroundColor: "#00205B",
    position: 'relative',
    marginBottom: -40,
  },
  curve: {
    position: 'absolute',
    top: -20,
    left: 0,
    right: 0,
    height: 200,
  },
  svg: {
    position: 'absolute',
    top: 0,
    left: 0.5,
  },
  buttonsContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 10,
    paddingBottom: 40,
    paddingHorizontal: 20,
  },
  registerAsText: {
    color: "#fff",
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  roleButtonsContainer: {
    flexDirection: 'row',
    gap: 20,
    marginBottom: 40,
  },
  roleButton: {
    backgroundColor: "#4EA5E4",
    paddingVertical: 14,
    paddingHorizontal: 40,
    borderRadius: 25,
    minWidth: 120,
    alignItems: 'center',
  },
  roleButtonActive: {
    backgroundColor: "#4EA5E4",
    borderWidth:3,
    borderColor:'#fff',
  },
  roleButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: '600',
  },
  registerButton: {
    backgroundColor: "#fff",
    paddingVertical: 18,
    paddingHorizontal: 60,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 5,
      height: 5
    },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 10,
  },
  registerButtonText: {
    color: "#00205B",
    fontSize: 20,
    fontWeight: '600',
  },
})